### ISSUE TITLE
store mode:file_store/data

### ISSUE THREAD

**Issue by jackfo** [seata/seata-samples#105]
Exception in thread "main" java.lang.IllegalArgumentException: unknown store mode:file_store/data
	at io.seata.core.store.StoreMode.valueof(StoreMode.java:48)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:84)
	at io.seata.server.Server.main(Server.java:76)

版本是https://github.com/seata/seata/releases/download/0.5.0/seata-server-0.5.0.tar.gz
在启动的时候出现了这个错误,启动seata-server.sh之时,已经修改了registry.conf里面type="nacos"为type="file"

**Comment by jackfo** [comment]
看了一下seata代码,关于STORE_MODE只有DB和FILE两种类型,改成FILE就可以运行
