### ISSUE TITLE
springcloud-jpa-seata中的子项目business-service和其他子项目启动后报错

### ISSUE THREAD

**Issue by jwrwst** [seata/seata-samples#110]
com.alibaba.fescar.common.exception.FrameworkException: can not register RM,err:can not connect to fescar-server.
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.doConnect(RmRpcClient.java:324) ~[fescar-core-0.4.2.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient.connect(RmRpcClient.java:289) ~[fescar-core-0.4.2.jar:na]
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingClient.reconnect(AbstractRpcRemotingClient.java:348) ~[fescar-core-0.4.2.jar:na]
	at com.alibaba.fescar.core.rpc.netty.RmRpcClient$1.run(RmRpcClient.java:150) [fescar-core-0.4.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]

====================服务启动日志如下=======================
11:11:18,718 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/C:/Users/DECHAO-LIU/Desktop/seata-server-0.5.0/conf/logback.xml]
11:11:18,718 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 1 minutes
11:11:18,728 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:11:18,730 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stdout]
11:11:18,774 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
11:11:18,776 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [seata-default]
11:11:18,785 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@152005629 - Archive files will be limited to [2048 MB] each.
11:11:18,787 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@152005629 - No compression will be used
11:11:18,788 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@152005629 - Will use the pattern C:/Users/DECHAO-LIU/logs/seata/seata-server.log.%d{yyyy-MM-dd}.%i for the active file
11:11:18,792 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@47f6473 - The date pattern is 'yyyy-MM-dd' from file name pattern 'C:/Users/DECHAO-LIU/logs/seata/seata-server.log.%d{yyyy-MM-dd}.%i'.
11:11:18,792 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@47f6473 - Roll-over at midnight.
11:11:18,795 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@47f6473 - Setting initial period to Mon May 06 11:11:01 CST 2019
11:11:18,799 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@152005629 - Cleaning on start up
11:11:18,799 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
11:11:18,800 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
11:11:18,800 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:11:18,801 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[seata-default] - Active log file name: C:\Users\DECHAO-LIU/logs/seata/seata-server.log
11:11:18,801 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[seata-default] - File property is set to [C:\Users\DECHAO-LIU/logs/seata/seata-server.log]
11:11:18,803 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [io.seata.server.store.FileTransactionStoreManager] to false
11:11:18,803 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - io.seata.server.store.FileTransactionStoreManager level set to INFO
11:11:18,803 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [seata-default] to Logger[io.seata.server.store.FileTransactionStoreManager]
11:11:18,803 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:11:18,803 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [seata-default] to Logger[ROOT]
11:11:18,803 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
11:11:18,803 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:11:18,804 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@15975490 - Registering current configuration as safe fallback point

2019-05-06 11:11:18.875 INFO [main]io.seata.common.loader.EnhancedServiceLoader.loadFile:193 -load ConfigurationProvider[Nacos] extension by class[io.seata.config.nacos.NacosConfigurationProvider]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.seata.core.rpc.netty.RpcServer.<init>(RpcServer.java:87)
        at io.seata.server.Server.main(Server.java:54)
Caused by: java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Unknown Source)
        at io.seata.core.rpc.netty.TransportProtocolType.valueOf(TransportProtocolType.java:25)
        at io.seata.core.rpc.netty.NettyBaseConfig.<clinit>(NettyBaseConfig.java:114)
        ... 2 more
PS C:\Users\DECHAO-LIU\Desktop\seata-server-0.5.0\bin>

**Comment by AndyLvVip** [comment]
#98 这个问题跟你的应该是一样的，已经解决了

**Comment by jwrwst** [comment]
已解决
