### ISSUE TITLE
项目工程一重启就时不时的出现io.seata.common.exception.FrameworkException: can not register RM,err:register error,role:RMROLE,err:cost 30948 ms为什吗呐

### ISSUE THREAD

**Issue by yahuishi** [seata/seata-samples#253]
io.seata.common.exception.FrameworkException: can not register RM,err:register error,role:RMROLE,err:cost 30948 ms
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:102) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:171) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient$1.run(AbstractRpcRemotingClient.java:113) [seata-all-0.9.0.jar:0.9.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.39.Final.jar:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

**Comment by xingfudeshi** [comment]
Which sample?

**Comment by xingfudeshi** [comment]
Will close this issue due to No response for a long time.

**Comment by zx0828** [comment]
请问下，解决了吗

**Comment by Garlichead** [comment]
> Which sample?

about this https://github.com/seata/seata-samples/tree/master/springcloud-eureka-feign-mybatis-seata
