### ISSUE TITLE
tcc sample keep blocking

### ISSUE THREAD

**Issue by dreamoftch** [seata/seata-samples#254]
i run the latest sample code(commit id is: 145b2cf95b1af3124f7d169c1339e0ed764f8efc) follow [the guide ](https://github.com/seata/seata-samples/tree/master/tcc/springboot-tcc-sample)

both seata server and the provider application run ok, but SpringbootTccTransactionApplication keeps blocking.

when i use jstack to find what happened, i see this:
```text
"main" #1 prio=5 os_prio=0 tid=0x000000000384a800 nid=0x564 waiting for monitor entry [0x000000000374e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:102)
        - waiting to lock <0x00000006c231ff20> (a java.lang.Object)
        at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:226)
        at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:233)
        at io.seata.rm.AbstractResourceManager.branchRegister(AbstractResourceManager.java:67)
        at io.seata.rm.DefaultResourceManager.branchRegister(DefaultResourceManager.java:96)
        at io.seata.rm.tcc.interceptor.ActionInterceptorHandler.doTccActionLogStore(ActionInterceptorHandler.java:118)
        at io.seata.rm.tcc.interceptor.ActionInterceptorHandler.proceed(ActionInterceptorHandler.java:69)
        at io.seata.spring.tcc.TccActionInterceptor.invoke(TccActionInterceptor.java:85)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.apache.dubbo.common.bytecode.proxy0$$EnhancerBySpringCGLIB$$539059da.prepare(<generated>)
        at io.seata.samples.tcc.springboot.dubbo.service.TccTransactionService.doTransactionCommit(TccTransactionService.java:31)
        at io.seata.samples.tcc.springboot.dubbo.service.TccTransactionService$$FastClassBySpringCGLIB$$e1c6fcc.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:104)
        at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:64)
        at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:101)
        at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:76)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at io.seata.samples.tcc.springboot.dubbo.service.TccTransactionService$$EnhancerBySpringCGLIB$$3a2dcf90.doTransactionCommit(<generated>)
        at io.seata.samples.tcc.springboot.dubbo.starter.SpringbootTccTransactionApplication.transactionCommitDemo(SpringbootTccTransactionApplication.java:51)
        at io.seata.samples.tcc.springboot.dubbo.starter.SpringbootTccTransactionApplication.main(SpringbootTccTransactionApplication.java:42)

   Locked ownable synchronizers:
        - None
```

after looking at the source code in `io.seata.core.rpc.netty.NettyClientChannelManager#acquireChannel`, i found that it blocked to get the object lock:
```java
        synchronized (channelLocks.get(serverAddress)) {
            return doConnect(serverAddress);
        }
```
i does not change any code locally, and confused about why this happen, 

could anyone help?

**Comment by dreamoftch** [comment]
i changed seata version from 0.9.0 to 0.8.0, it works

**Comment by slievrly** [comment]
@dreamoftch please update to the latest version.
