### ISSUE TITLE
springcloud-eureka-feign-mybatis-seata demo 运行storage-server报错

### ISSUE THREAD

**Issue by 604152021** [seata/seata-samples#280]
按照操作手册配置以后，在windows环境下运行http://localhost:8180/order/create?userId=1&productId=1&count=10&money=100 报错，报错信息如下所示：烦请各位大神指导一下

2019-12-04 19:07:51.524  INFO 18312 --- [nio-8182-exec-2] i.s.sample.service.StorageServiceImpl    : ------->扣减库存开始
2019-12-04 19:07:52.526  INFO 18312 --- [nio-8182-exec-6] i.s.sample.service.StorageServiceImpl    : ------->扣减库存开始
2019-12-04 19:07:56.661 ERROR 18312 --- [nio-8182-exec-2] i.s.r.d.exec.AbstractDMLBaseExecutor     : execute executeAutoCommitTrue error:io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = 169.254.70.104:8091:2029185067 status = Rollbacking whi ]

java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not register branch into global session xid = 169.254.70.104:8091:2029185067 status = Rollbacking whi ]
	at io.seata.rm.datasource.ConnectionProxy.recognizeLockKeyConflictException(ConnectionProxy.java:148) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:210) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:187) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:175) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy$$Lambda$519/2001280273.call(Unknown Source) ~[na:na]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:278) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:174) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:92) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$$Lambda$515/781005752.call(Unknown Source) ~[na:na]
	at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:288) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:135) ~[seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:90) [seata-all-0.9.0.jar:0.9.0]
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:58) [seata-all-0.9.0.jar:0.9.0]

**Comment by 604152021** [comment]
已解决是数据库权限的问题，seata-server sotre 选择DB ，如果此时db是阿里云的RDS就会有问题。
