### ISSUE TITLE
DubboBusinessTester无法从注册中心获取到orderService和storageService

### ISSUE THREAD

**Issue by SnailDHC** [seata/seata-samples#298]
os: windows10
zookeeper: 3.4.5
nacos-server: 1.1.4
seata-server: 1.0.0

我分别尝试了dubbo模块和nacos模块，按照account - storage -order的顺序启动，一切正常，可以看到有三个provider和一个comsumer，但是当我启动DubboBusinessTester时，就会报找不到可用服务的错误。
dubbo模块，使用zk：
`Exception in thread "main" org.apache.dubbo.rpc.RpcException: No provider available from registry localhost:2181 for service io.seata.samples.dubbo.service.StorageService on consumer 169.254.240.8 use dubbo version 2.7.1, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:552)
	at org.apache.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:82)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:274)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:239)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:76)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57)
	at org.apache.dubbo.common.bytecode.proxy1.deduct(proxy1.java)
	at io.seata.samples.dubbo.service.impl.BusinessServiceImpl.purchase(BusinessServiceImpl.java:44)
	at io.seata.samples.dubbo.service.impl.BusinessServiceImpl$$FastClassBySpringCGLIB$$1af2d32f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor$1.execute(GlobalTransactionalInterceptor.java:109)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:64)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:106)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:81)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.seata.samples.dubbo.service.impl.BusinessServiceImpl$$EnhancerBySpringCGLIB$$964ace00.purchase(<generated>)
	at io.seata.samples.dubbo.starter.DubboBusinessTester.main(DubboBusinessTester.java:38)`

nacos模块，使用nacos：
`Exception in thread "main" io.seata.common.exception.FrameworkException: No available service
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.loadBalance(AbstractRpcRemotingClient.java:282)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:228)
	at io.seata.core.rpc.netty.AbstractRpcRemotingClient.sendMsgWithResponse(AbstractRpcRemotingClient.java:236)
	at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95)
	at io.seata.tm.DefaultTransactionManager.begin(DefaultTransactionManager.java:53)
	at io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:102)
	at io.seata.tm.api.TransactionalTemplate.beginTransaction(TransactionalTemplate.java:123)
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:58)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:106)
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:81)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at io.seata.samples.nacos.service.impl.BusinessServiceImpl$$EnhancerBySpringCGLIB$$36fdb36f.purchase(<generated>)
	at io.seata.samples.nacos.starter.DubboBusinessTester.main(DubboBusinessTester.java:39)`

**Comment by q294881866** [comment]
考虑下配置中心地址是否一致

**Comment by SnailDHC** [comment]
> 考虑下配置中心地址是否一致

我使用的是demo里面的配置，然后在本地启动的nacos，我确定过地址是一致的

**Comment by SnailDHC** [comment]
调整了seata-server和模块中的registry.conf，nacos模块已经正常运行

**Comment by HyberLinker** [comment]
> 调整了seata-server和模块中的registry.conf，nacos模块已经正常运行

请问，最后是怎么解决了。我把seata-server和模块中的registry.conf都统一修改了还是报错
io.seata.common.exception.FrameworkException: No available service
