### ISSUE TITLE
java.lang.RuntimeException: rm client is not connected.

### ISSUE THREAD

**Issue by zx0828** [seata/seata-samples#301]
2020-01-16 15:18:02.906 INFO [RetryRollbacking_1]io.seata.core.rpc.ChannelManager.getChannel:331 -No channel is availabl
e for resource[jdbc:mysql://xxx.xxx.xxx.xxx:3307/seata]
2020-01-16 15:18:02.908 ERROR[RetryRollbacking_1]io.seata.server.coordinator.DefaultCore.doGlobalRollback:436 -Exception
 rollbacking branch xid=192.168.59.1:8091:2032882682 branchId=2032882757
java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://xxx.xxx.xxx.xxx:3306/seata,clientId:dubbo-demo-
account-service:192.168.59.1:63721
        at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:216)
        at io.seata.core.rpc.netty.RpcServer.sendSyncRequest(RpcServer.java:266)
        at io.seata.server.coordinator.DefaultCoordinator.branchRollback(DefaultCoordinator.java:312)
        at io.seata.server.coordinator.DefaultCore.doGlobalRollback(DefaultCore.java:411)
        at io.seata.server.coordinator.DefaultCoordinator.handleRetryRollbacking(DefaultCoordinator.java:397)
        at io.seata.server.coordinator.DefaultCoordinator.lambda$init$1(DefaultCoordinator.java:497)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

**Comment by q294881866** [comment]
什么场景哪个demo报错的，怎么复现？

**Comment by q294881866** [comment]
请下载 seata release 版本 通过 bin/seata-server 脚本启动可以解决，io.seata.server.Server启动我看一下

**Comment by q294881866** [comment]
在你项目根目录应该可以找到这个文件，把它删了。
sessionStore/root.data

**Comment by q294881866** [comment]
问题原因  
io.seata.server.session.SessionHolder#init
String sessionStorePath = CONFIG.getConfig("store.file.dir", "sessionStore");
删除 sessionStore/root.data 或者用 seata  bin/seata-server启动都可以解决
