### ISSUE TITLE
spring boot项目中使用GlobalTransactional时，启动项目，不间断的报警告信息。

### ISSUE THREAD

**Issue by chusen12** [seata/seata-samples#310]
启动项目后，不停的输出警告，打印Could not found property service.disableGlobalTransaction, try to use default value instead.
但是在配置文件里面已经配上了seata.service.disable-global-transaction=false。还是会不停的打印WARN

**Comment by qingshenqin** [comment]
以最新的1.1.0 seata版本为例，在测试过程中发现，seata似乎已经废弃了以“-”分隔的属性，如“disable-global-transaction”，应该改为以驼峰的命名“disableGlobalTransaction”。以file.config配置为例。在service下添加disableGlobalTransaction=false即好,例如：service{disableGlobalTransaction = false}

**Comment by yufei240** [comment]
还是不知道什么原因，项目加了全局事务注解，但是启动不了
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:84) ~[seata-spring-boot-starter-1.0.0.jar:na]
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.addConfigListener(<generated>) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:225) ~[seata-all-1.1.0.jar:1.1.0]
	... 35 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig(<generated>) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.config.FileConfiguration.addConfigListener(FileConfiguration.java:180) ~[seata-all-1.1.0.jar:1.1.0]
	... 42 common frames omitted

 @Override
    public void addConfigListener(String dataId, ConfigurationChangeListener listener) {
        if (null == dataId || null == listener) {
            return;
        }
        configListenersMap.putIfAbsent(dataId, new ConcurrentSet<>());
        configListenersMap.get(dataId).add(listener);
        //这边获取disableGlobalTransaction属性时报错了
        listenedConfigMap.put(dataId, ConfigurationFactory.getInstance().getConfig(dataId));
        FileListener fileListener = new FileListener(dataId, listener);
        fileListener.onProcessEvent(new ConfigurationChangeEvent());
    }

**Comment by qingshenqin** [comment]
hello，给出的信息不够全面。有几点非常重要的：
1.请问你是用spring cloud 体系，还是单单是spring boot，两者配置还有不一样的。
2.可以参照对应的demo检查下，这个demo是这个地址的demo，https://github.com/seata/seata-samples。seata-parent下的demo是没什么参考价值
3.Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
&nbsp;这里有一个错误，先解决，可能是file.config 里面配错了，file.config里面的配置1.0之后和0.8还是有点区别，以seata-server包下的提供案例为主

4.建议先使用demo中出现的最简单的方式，跑起来先




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yufei"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上11:23
收件人: "seata/seata-samples"<seata-samples@noreply.github.com&gt;; 
抄送: "karl"<632929757@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [seata/seata-samples] spring boot项目中使用GlobalTransactional时，启动项目，不间断的报警告信息。 (#310)





 
还是不知道什么原因，项目加了全局事务注解，但是启动不了
 Caused by: java.lang.reflect.InvocationTargetException: null
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
 at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
 at io.seata.spring.boot.autoconfigure.provider.SpringBootConfigurationProvider$1.intercept(SpringBootConfigurationProvider.java:84) ~[seata-spring-boot-starter-1.0.0.jar:na]
 at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.addConfigListener() ~[seata-all-1.1.0.jar:1.1.0]
 at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:225) ~[seata-all-1.1.0.jar:1.1.0]
 ... 35 common frames omitted
 Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
 at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getConfig() ~[seata-all-1.1.0.jar:1.1.0]
 at io.seata.config.FileConfiguration.addConfigListener(FileConfiguration.java:180) ~[seata-all-1.1.0.jar:1.1.0]
 ... 42 common frames omitted
 
@override
 public void addConfigListener(String dataId, ConfigurationChangeListener listener) {
 if (null == dataId || null == listener) {
 return;
 }
 configListenersMap.putIfAbsent(dataId, new ConcurrentSet<&gt;());
 configListenersMap.get(dataId).add(listener);
 //这边获取disableGlobalTransaction属性时报错了
 listenedConfigMap.put(dataId, ConfigurationFactory.getInstance().getConfig(dataId));
 FileListener fileListener = new FileListener(dataId, listener);
 fileListener.onProcessEvent(new ConfigurationChangeEvent());
 }

**Comment by zouHero** [comment]
> 启动项目后，不停的输出警告，打印Could not found property service.disableGlobalTransaction, try to use default value instead.
> 但是在配置文件里面已经配上了seata.service.disable-global-transaction=false。还是会不停的打印WARN

这个问题我也碰到了，请问是怎么解决的

**Comment by pencilso** [comment]
我也遇到这个问题了，而且我用的是seata-server包下的提供案例，都没改那个file.conf，但是就是运行不起来，有点懵。

**Comment by pencilso** [comment]
老哥解决这个问题了吗

**Comment by limuzi19942018** [comment]
我也遇到了，请问各位老哥解决了吗

**Comment by liwai1206** [comment]
> 

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at io.seata.config.ConfigurationCache.lambda$proxy$1(ConfigurationCache.java:108) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.config.Configuration$$EnhancerByCGLIB$$dc6b8697.getLatestConfig(<generated>) ~[cglib-3.1.jar:1.4.2]
	at io.seata.config.FileConfiguration$FileListener.onChangeEvent(FileConfiguration.java:399) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.config.ConfigurationChangeListener.lambda$onProcessEvent$0(ConfigurationChangeListener.java:62) [seata-all-1.4.2.jar:1.4.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at io.seata.config.FileConfiguration$$EnhancerByCGLIB$$862af1eb.getLatestConfig(<generated>) ~[seata-all-1.4.2.jar:1.4.2]
	... 14 common frames omitted

同样是报这个错，有老哥解决了的吗？
