### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by ronaldo123321** [seata/seata-samples#317]
使用springcloud-eureka-feign-mybatis-seata的配置嵌入自己的服务中，启动时报如下错误，这是什么原因导致的？
`Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkPositive(ILjava/lang/String;)I
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:44) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.availableProcessors(NettyRuntime.java:70) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.netty.util.NettyRuntime.availableProcessors(NettyRuntime.java:98) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
	at io.seata.core.rpc.netty.NettyBaseConfig$WorkThreadMode.<clinit>(NettyBaseConfig.java:190) ~[seata-all-1.1.0.jar:1.1.0]
	at io.seata.core.rpc.netty.NettyBaseConfig.<clinit>(NettyBaseConfig.java:117) ~[seata-all-1.1.0.jar:1.1.0]`

**Comment by slievrly** [comment]
@ronaldo123321 check the Netty dependency，
