### ISSUE TITLE
dubbo模块，DubboBusinessTester启动报错，Caused by: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.rm.datasource.undo.UndoLogParser

### ISSUE THREAD

**Issue by weimengchao** [seata/seata-samples#346]
![image](https://user-images.githubusercontent.com/18591491/81523298-065bd500-9380-11ea-973b-0a17f1960ae1.png)

**Comment by weimengchao** [comment]
[INFO ] 2020-05-11 11:17:51,612 method:io.seata.tm.api.DefaultGlobalTransaction.rollback(DefaultGlobalTransaction.java:179)
	[100.64.0.132:8091:2011358770] rollback status: Rollbacked
	Exception in thread "main" java.lang.RuntimeException: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [update storage_tbl set count = count - ? where commodity_code = ?]; SQL state [null]; error code [0]; java.lang.ExceptionInInitializerError; nested exception is java.sql.SQLException: java.lang.ExceptionInInitializerError
	org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [update storage_tbl set count = count - ? where commodity_code = ?]; SQL state [null]; error code [0]; java.lang.ExceptionInInitializerError; nested exception is java.sql.SQLException: java.lang.ExceptionInInitializerError
		at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
		at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
		at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
		at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
		at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
		at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862)
		at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:917)
		at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:927)
		at io.seata.samples.dubbo.service.impl.StorageServiceImpl.deduct(StorageServiceImpl.java:52)
		at org.apache.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
		at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
		at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
		at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
		at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
		at com.alibaba.dubbo.rpc.Invoker$CompatibleInvoker.invoke(Invoker.java:55)
		at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:43)
		at com.alibaba.dubbo.rpc.Filter.invoke(Filter.java:29)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at io.seata.integration.dubbo.ApacheDubboTransactionPropagationFilter.invoke(ApacheDubboTransactionPropagationFilter.java:65)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:44)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:102)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:149)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:150)
		at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
		at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
		at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
		at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.sql.SQLException: java.lang.ExceptionInInitializerError
		at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:226)
		at io.seata.rm.datasource.ConnectionProxy.doCommit(ConnectionProxy.java:196)
		at io.seata.rm.datasource.ConnectionProxy.lambda$commit$0(ConnectionProxy.java:184)
		at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.execute(ConnectionProxy.java:289)
		at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:183)
		at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$0(AbstractDMLBaseExecutor.java:106)
		at io.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:299)
		at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:149)
		at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:104)
		at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:72)
		at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:110)
		at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:108)
		at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:49)
		at io.seata.rm.datasource.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:64)
		at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:867)
		at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
		... 39 more
	Caused by: java.lang.ExceptionInInitializerError
		at io.seata.rm.datasource.undo.UndoLogParserFactory.getInstance(UndoLogParserFactory.java:50)
		at io.seata.rm.datasource.undo.AbstractUndoLogManager.flushUndoLogs(AbstractUndoLogManager.java:213)
		at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:221)
		... 54 more
	Caused by: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.rm.datasource.undo.UndoLogParser

		at org.apache.dubbo.rpc.filter.ExceptionFilter.onMessage(ExceptionFilter.java:98)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.lambda$invoke$0(ProtocolFilterWrapper.java:109)
		at org.apache.dubbo.rpc.AsyncRpcResult.lambda$whenCompleteWithContext$0(AsyncRpcResult.java:193)
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
		at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
		at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
		at org.apache.dubbo.rpc.AsyncRpcResult.whenCompleteWithContext(AsyncRpcResult.java:191)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:96)
		at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:44)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:102)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:149)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
		at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
		at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:150)
		at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
		at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
		at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
		at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

**Comment by weimengchao** [comment]
修改file.conf，指定logSerialization = "fastjson"
