### ISSUE TITLE
seata启动MySQL报错

### ISSUE THREAD

**Issue by chuanzh** [seata/seata-samples#359]
修改file.conf配置，（此MySQL账号是可以连接的）如下：
db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "druid"
    ## mysql/oracle/postgresql/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.jdbc.Driver"
    url = "jdbc:mysql://172.16.245.85:3306/seata"
    user = "seata"
    password = "123456"
    minConn = 5
    maxConn = 30
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
  }

启动的时候报如下错误：
2020-06-19 09:06:23.262 WARN [main]com.alibaba.druid.pool.DruidDataSource.getConnectionDirect:1277 -get connection timeout retry : 1
2020-06-19 09:06:23.331 ERROR[Druid-ConnectionPool-Create-1423561005]com.alibaba.druid.pool.DruidDataSource.run:2507 -create connection SQLException, url: jdbc:mysql://172.16.245.85:3306/seata, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:958)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2316)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1570)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1636)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2505)
Caused by: java.lang.NullPointerException: null
	at com.mysql.jdbc.ConnectionImpl.getServerCharset(ConnectionImpl.java:2989)
	at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1802)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2239)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2270)
	... 13 common frames omitted

**Comment by sukang555** [comment]
我的错误也是这个，配置没写错就是连不上

**Comment by sukang555** [comment]
lib/jdbc 下边有两个connect包  可能是connect包和sql版本不对应

**Comment by chuanzh** [comment]
我安装的是MySQL8，把连接配置改成下面的，现在可以启动了：
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "druid"
    ## mysql/oracle/postgresql/h2/oceanbase etc.
    dbType = "mysql"
    driverClassName = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://172.16.245.85:3306/seata?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=UTC"
    user = "seata"
    password = "123456"
    minConn = 5
    maxConn = 30
    globalTable = "global_table"
    branchTable = "branch_table"
    lockTable = "lock_table"
    queryLimit = 100
  }

**Comment by javahuipaoren** [comment]
我的seata启动也报连接mysql失败错误，总是报空指针，感觉是版本问题。
seata版本0.9.0，mysql 8.0.20
`java.lang.NullPointerException: null
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1518)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1272)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1252)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1242)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:89)
	at io.seata.core.store.db.LogStoreDataBaseDAO.queryGlobalTransactionDO(LogStoreDataBaseDAO.java:208)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.readSession(DatabaseTransactionStoreManager.java:174)
	at io.seata.server.store.db.DatabaseTransactionStoreManager.readSession(DatabaseTransactionStoreManager.java:203)
	at io.seata.server.session.db.DataBaseSessionManager.findGlobalSessions(DataBaseSessionManager.java:183)
	at io.seata.server.session.db.DataBaseSessionManager.allSessions(DataBaseSessionManager.java:166)
	at io.seata.server.coordinator.DefaultCoordinator.handleRetryCommitting(DefaultCoordinator.java:398)
	at io.seata.server.coordinator.DefaultCoordinator.lambda$init$2(DefaultCoordinator.java:494)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by javahuipaoren** [comment]
找到原因了，因为seata-server-0.9.0版本lib下mysql驱动mysql-connector-java是5.1.30版本的，然而我用的mysql是8.0.20版本，所以要把seata/lib下的mysql-connector-java驱动换成mysql8.0.20的驱动即可。seata/conf/file.conf下db已改好的配置不用再修改。
附已修改好的file.conf配置：
`## database store
  db {
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp) etc.
    datasource = "druid"
    ## mysql/oracle/h2/oceanbase etc.
    db-type = "mysql"
    driver-class-name = "com.mysql.cj.jdbc.Driver"
    url = "jdbc:mysql://127.0.0.1:3306/seata?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=UTC"
    user = "root"
    password = "123456"
    min-conn = 1
    max-conn = 3
    global.table = "global_table"
    branch.table = "branch_table"
    lock-table = "lock_table"
    query-limit = 100
  }`

**Comment by Micron818** [comment]
1.4.2版本，连mysql8遇到同样错误，更正配置的driverClassName = "com.mysql.cj.jdbc.Driver"，注意有cj的，连接成功
