### ISSUE TITLE
引入seata后，正常的请求openfeign全进入fallback

### ISSUE THREAD

**Issue by hejunyuan** [seata/seata-samples#382]
Caused by: java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: 192.168.226.1
	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:90) ~[spring-cloud-openfeign-core-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.alibaba.cloud.seata.feign.SeataLoadBalancerFeignClient.execute(SeataLoadBalancerFeignClient.java:45) ~[spring-cloud-starter-alibaba-seata-2.2.1.RELEASE.jar:2.2.1.RELEASE]

**Comment by chenzongneng** [comment]
我也遇到这个情况,请问解决了吗
