### ISSUE TITLE
官网的seata官网的说明进行，运行seata-samples代码中的工程启动出现以下错误

### ISSUE THREAD

**Issue by yzsunlight** [seata/seata-samples#453]
`Exception in thread "main" org.apache.dubbo.rpc.RpcException: Failed to invoke the method deduct in the service io.seata.samples.dubbo.service.StorageService. No provider available for the service io.seata.samples.dubbo.service.StorageService from registry 224.5.6.7:1234 on the consumer 172.17.8.177 using the dubbo version 2.7.8. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:283)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:59)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:260)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy1.deduct(proxy1.java)
	at io.seata.samples.dubbo.service.impl.BusinessServiceImpl.purchase(BusinessServiceImpl.java:44)
	at io.seata.samples.dubbo.service.impl.BusinessServiceImpl$$FastClassBySpringCGLIB$$1af2d32f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)`

使用的是seata-samples\dubbo工程，StorageService 服务已经正常运行并注册，不知道哪里出了问题

**Comment by Pinocchio2018** [comment]
@yzsunlight 你好。试下这样
```
dubbo使用multicast找不到生产者
启动命令增加

-Djava.net.preferIPv4Stack=true
```
