### ISSUE TITLE
seata-samples-dubbo启动报错

### ISSUE THREAD

**Issue by julixiansheng** [seata/seata-samples#575]
启动DubboStockServiceStarter报错：
Caused by: java.lang.NoSuchMethodError: org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.setClassValuesAsString(Z)V
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.<init>(ReferenceAnnotationBeanPostProcessor.java:106)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 15 more
查询资料后升级spring-context-support版本为：1.0.11后不报错。
但是出现了新的报错：
Caused by: java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
	at io.seata.config.nacos.NacosConfigurationProvider.provide(NacosConfigurationProvider.java:29)
	at io.seata.config.ConfigurationFactory.buildConfiguration(ConfigurationFactory.java:131)
	at io.seata.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:94)
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:87)
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:132)
	at io.seata.spring.annotation.GlobalTransactionScanner.<init>(GlobalTransactionScanner.java:121)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 17 more
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.api.exception.NacosException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more****

不知道从哪儿下手了。。。

**Comment by leizhiyuan** [comment]
Please update the code for the example and test it again. No changes need to be made at the moment, as it has already been tested successfully.
